Homebrew Tap for Palm OS Utilities
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This repository contains Homebrew formulae for working with Palm OS devices.

pilot-link
^^^^^^^^^^

pilot-link is a suite of tools for connecting to Palm OS devices on Unix-like
systems. The original website (http://www.pilot-link.org) is now defunct, but
you can refer to the man pages (e.g.
http://manpages.ubuntu.com/manpages/en/man1/pilot-xfer.1.html[here]) and online
resources for help. A good place to start would be the
http://www.tldp.org/HOWTO/PalmOS-HOWTO/pilotlink.html[TLDP pilot-link HOWTO].

To install:
----
$ brew tap jichu4n/palm-os
$ brew install pilot-link
----

prc-tools
^^^^^^^^^

http://prc-tools.sourceforge.net/[prc-tools] is a collection of tools supporting
C and C++ programming for Palm OS. It supplies a full GCC cross-compilation
toolchain for https://en.wikipedia.org/wiki/Motorola_68000_series[m68k] and
https://en.wikipedia.org/wiki/ARM_architecture[ARM], as well as Palm OS-specific
utilities.

This formula uses the
https://github.com/jichu4n/prc-tools-remix[jichu4n/prc-tools-remix] codebase,
which patches the last prc-tools release to compile and run on modern Linux and
macOS.

To install:
----
$ brew tap jichu4n/palm-os
$ brew install prc-tools
----

The compilation takes about 10-15 minutes, as measured on a 2014 MacBook Pro
(Core i5 Haswell).

After install, prc-tools will look for Palm OS SDK files in
`/usr/local/opt/prc-tools/palmdev`. You can either download and extract the SDK
files yourself, or use the `palm-os-sdk` formula below.

palm-os-sdk
^^^^^^^^^^^

This formula will install an archive of the Palm OS SDK from
https://github.com/jichu4n/palm-os-sdk[jichu4n/palm-os-sdk] for use with
prc-tools.

To install:
----
$ brew tap jichu4n/palm-os
$ brew install palm-os-sdk
----

You will then need to run `palmdev-prep` to let prc-tools know about the SDK
location.

pilrc
^^^^^

http://pilrc.sourceforge.net/[PilRC] is a Palm OS resource compiler. It compiles
a textual description of Palm OS forms, bitmaps, fonts, and other resources into
a binary form that can be included in an application or library.

To install:
----
$ brew tap jichu4n/palm-os
$ brew install pilrc
----

